SyntaxError: name 'pokeball' is used prior to global declaration Traceback (most recent call last):   File "/usr/src/app/run.py", line 5, in <module>     from TwitchChannelPointsMiner import TwitchChannelPointsMiner   File "/usr/src/app/TwitchChannelPointsMiner/__init__.py", line 3, in <module>     from .TwitchChannelPointsMiner import TwitchChannelPointsMiner   File "/usr/src/app/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 14, in <module>     from TwitchChannelPointsMiner.classes.Chat import ChatPresence, ThreadChat   File "/usr/src/app/TwitchChannelPointsMiner/classes/Chat.py", line 120     global pokeball     ^^^^^^^^^^^^^^^ SyntaxError: name 'pokeball' is used prior to global declaration